### ISSUE TITLE
Do data ROOT files need to be pre-mixed?

### ISSUE THREAD

**Issue by jmduarte** [hqucms/weaver#1]
Hi @hqucms. Really nice code!

I'm wondering about whether the Data ROOT files need to be pre-mixed or if this can run directly on the output of crab jobs, which obviously will have root files divided by sample:
```
root file from QCD pThat bin 1
root file from QCD pThat bin 1
....
root file from QCD pThat bin 1
root file from Higgs sample 1
...
```

In the past, I would use the `mergeSamples` utility from Jan to ensure they were properly mixed up so the training wouldn't see events from just one sample at a time (populating a full batch). Does this take care of that now?

Thanks!
Javier

@cmantill

**Comment by hqucms** [comment]
Hi @jmduarte,

There is no need to mix the input files -- by default the data loader will read a small fraction (e..g., 1%) of events from each input ROOT file, shuffle them, so each batch will get all types of events (for more details please see the options in [0]). However this comes at a slight cost of speed, so if you happen to have pre-mixed files you could also set `--fetch-by-files --fetch-step 10` (i.e., read file by file, mix after reading every 10 files) to make it a bit faster.

[0] https://github.com/hqucms/weaver/blob/master/utils/dataset.py#L231-L238
Also in the command line options: https://github.com/hqucms/weaver/blob/master/train.py#L30-L35
